# Generated by Django 4.0.6 on 2022-11-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='post_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
