# Generated by Django 3.2.15 on 2023-01-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprofile',
            old_name='server',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='gameprofile',
            old_name='regions',
            new_name='servers',
        ),
    ]
