# Generated by Django 4.0.6 on 2022-12-28 07:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_header_pic',
            field=models.ImageField(
                blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='community',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='post_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                blank=True, default='', max_length=500, null=True), blank=True, default=list, null=True, size=None),
        ),

    ]
