# Generated by Django 3.2.15 on 2023-01-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
