# Generated by Django 4.0.6 on 2022-12-29 06:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0002_community_community_header_pic_community_post_date_and_more'),
    ]

    operations = [
    ]
