# Generated by Django 4.0.6 on 2022-11-10 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0002_community_post_date_community_post_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='post_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
