# Generated by Django 4.0.6 on 2022-11-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0003_alter_community_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_header_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
