# Generated by Django 4.0.6 on 2023-01-04 06:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0003_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [

         ]
