# Generated by Django 4.0.6 on 2022-11-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0004_community_community_header_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured_communities',
            field=models.ManyToManyField(blank=True, default=None, related_name='featuredCommunities', to='page3.community'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(blank=True, default=None, related_name='communities', to='page3.community'),
        ),
    ]
