# Generated by Django 4.0.6 on 2023-01-09 08:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0005_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [
        
    ]
