# Generated by Django 4.0.6 on 2023-01-11 02:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0009_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='gameprofile',
            name='peak_rank',
            field=models.CharField(choices=[('Val', [('IRON', 'Iron'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum '), ('Diamond', 'Diamond'), ('Asencdant', 'Asencdant'), ('Immortal', 'Immortal'), ('Radiant', 'Radiant')]), ('COD', [('Rookie', 'Rookie'), ('Veteran', 'Veteran'), ('Elite', 'Elite'), ('Pro', 'Pro'), ('Master', 'Master'), ('Grandmaster', 'Grandmaster'), ('Legendary', 'Legendary')]), ('LOL', [(
                'IRON', 'Iron'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum '), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Grandmaster', 'Grandmaster'), ('Challenger', 'Challenger')]), ('CS', [('Silver', 'Silver'), ('Gold', 'Gold'), ('Master Guardian', 'Master Guardian'), ('Distinguished Master Guardian', 'Distinguished Master Guardian'), ('Legendary', 'Legendary'), ('Elite', 'Elite')])], default='', max_length=50),
        ),
    ]
