# Generated by Django 4.0.6 on 2023-01-11 03:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0013_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprofile',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
