# Generated by Django 4.0.6 on 2023-01-14 04:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0014_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='post_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                blank=True, default='', max_length=50, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
