# Generated by Django 4.0.6 on 2023-01-27 02:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0016_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [

        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_messages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(
                    blank=True, default='', max_length=1000, null=True), blank=True, default=list, null=True, size=None)),
                ('user', models.OneToOneField(
                    default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
