# Generated by Django 4.0.6 on 2023-01-27 04:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0017_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='notifications',
            name='unread_messages',
        ),
        migrations.AddField(
            model_name='notifications',
            name='unread_messages',
            field=models.ManyToManyField(
                blank=True, default=None, related_name='unread_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
