# Generated by Django 4.0.6 on 2023-01-30 08:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import page3.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0025_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='profile',
            name='last_chat_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(
                blank=True, default=page3.models.Profile.temp_dict, max_length=30, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
