# Generated by Django 4.0.6 on 2023-02-02 03:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0026_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_chat_with',
            field=models.CharField(
                blank=True, default=None, max_length=10, null=True),
        ), ]
