# Generated by Django 4.0.6 on 2023-02-11 02:31

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0027_gameprofile_achievements_gameprofile_additional_info_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='notifications',
            name='unviewed_likes',
            field=models.ManyToManyField(
                blank=True, default=None, related_name='new_likes', to='page3.post'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='unviewed_vouches',
            field=models.ManyToManyField(
                blank=True, default=None, related_name='new_vouches', to=settings.AUTH_USER_MODEL),
        ),

    ]
