# Generated by Django 3.2.15 on 2023-02-09 08:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page3', '0030_auto_20230209_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='new_likes',
            new_name='unviewed_likes',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='new_vouches',
            new_name='unviewed_vouches',
        ),
        
    ]
